import regressionJson from './data/regression.json'
import walksJson from './data/walks.json'
import type { Fit, Walk } from './types'

// Generated by scripts/export_dashboard_data.py; re-run it after cleaning new data
export const WALKS: Walk[] = (walksJson as Omit<Walk, 'time'>[]).map((w) => ({
  ...w,
  time: Date.parse(w.startDate),
}))

export const REGRESSION = regressionJson as {
  calories: Fit
  duration: Fit
  points: { distance_km: number; calories_total: number; duration: number }[]
}

export const YEARS = [...new Set(WALKS.map((w) => w.year))].sort()
